### ISSUE TITLE
Importing older projects metadata from Excel into YuanRui

### ISSUE THREAD

**Issue by fasteddys** [yuanrui/CodeGenerator#5]
Hello this a nice place to keep the meta data of my projects. I used to have an excel spreadsheet with the table names & two Cols for the name and type, I would like to import that into yaunrui - so I can generate the projects from here.

`NameCol`
`TypeCol`

How can I template this excel sheet to a simple C# POCO model class with the name and type

**Comment by yuanrui** [comment]
Generate excel code, need specify a special format, It`s a limited usage scenarios. So, using Excel formulas might be a good idea :-)

**Comment by fasteddys** [comment]
let me clarify, I used to have an excel spreadsheet with the table names & two Cols for the name and type, I would like to import that via your codegen project - so I can generate the model objects from from here.

```
Excel Col - ClassName 
Excel Col - AtrributeName
Excel Col - Type
```

How can I template this excel sheet to a simple C# POCO model class with the name and type

**Comment by yuanrui** [comment]
Use ado.net provider Microsoft.Jet.OLEDB(need to install) read metadata from Excel may be practicable. Could you implement this feature? Pull request welcome.

Microsoft Access Database Engine 2010: https://www.microsoft.com/en-us/download/details.aspx?id=13255
Microsoft Access Database Engine 2016: https://www.microsoft.com/en-us/download/details.aspx?id=54920

**Comment by fasteddys** [comment]
Hello I am trying I can read the data, but not understand where to insert so it shows up in your tree and pattern in your generator.

Do you have a diagram of the code/architecture or components on `where we should make changes to correctly make a plugin or addin code`

also would be nice to make a plugins for your tool
